### ISSUE TITLE
Get custom data in layout.php

### ISSUE THREAD

**Issue by leonardoballand** [axessweb/W#4]
Hi, I need to get custom data about global informations from my website. I need to get theses informations from my SQL database. Where can I do it without modifying your framework code?

Thanks

**Comment by axessweb** [comment]
Salut, 
On peut causer en français :-) 

Tu veux accéder à quoi comme info depuis le layout ?

**Comment by leonardoballand** [comment]
Hey ! J'ai des informations générales du site à administrer depuis le dashboard. Du genre nom du site, logo à uploader, description, balises Meta, etc... Plus des sections du site à organiser selon d'autres paramètres également en base de données. Certaines infos doivent s'afficher directement dans le layout et être accessibles dans n'importe quelle view

**Comment by digitalz4k** [comment]
En fait c'est bon j'ai créé un controller global et j'ai rendu accessible les données de la DB par celui-ci

**Comment by axessweb** [comment]
Parfait !
